image: nixos/nix:latest

stages:
  - basic
  - build

basic:hlint:
  stage: basic
  before_script:
    - nix-env -iA nixpkgs.hlint
  script:
    - hlint Lib Exec

basic:brittany:
  stage: basic
  before_script:
    - nix-env -iA nixpkgs.haskellPackages.brittany nixpkgs.git
  script:
    - find Exec Lib -name '*.hs' -exec brittany --write-mode=inplace {} \;
    - git diff --exit-code

basic:cabal2nix:
  stage: basic
  before_script:
    - nix-env -iA nixpkgs.cabal2nix nixpkgs.git
  script:
    - cabal2nix . > default.nix
    - git diff --exit-code

build:nix:
  stage: build
  script:
    - nix-build release.nix
